### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by cowwoc** [mariten/kanatools-java#11]
Please publish this library to Maven Central. See http://central.sonatype.org/pages/ossrh-guide.html if you've never done this before.

**Comment by mariten** [comment]
Thanks for the idea @cowwoc -- I'm interested in increasing visibility of this library so this is helpful

**Comment by mariten** [comment]
Hi @cowwoc 

Apologies I've been distracted by a lot of other things recently and haven't had much time for this repo.  The process of using Sonatype is quite convoluted and kind of archaic, I started playing around with it about a week ago and have now finally succeeded!

http://search.maven.org/#artifactdetails|com.mariten|kanatools|1.3.0|jar

This repository is now includable in your `pom.xml` like this:

``` xml
<dependency>
  <groupId>com.mariten</groupId>
  <artifactId>kanatools</artifactId>
  <version>1.3.0</version>
</dependency>
```

Thanks for contributing this issue!
