### ISSUE TITLE
Handling of long vowel sounds

### ISSUE THREAD

**Issue by stephenmac7** [mariten/kanatools-java#13]
When converting from Katakana to Hiragana, it seems that the library doesn't handle long vowel sounds properly. For example アタラシー becomes あたらしー but should be あたらしい.

**Comment by mariten** [comment]
Hi @stephenmac7 , thanks for commenting.  Apologies for the late response, my attention has been elsewhere over the last few months.

**To summarize**, the purpose of this library is one-to-one character conversion, not translation, which I feel this phenomenon falls into and is not the purpose of the this library.

**To elaborate**:
This repository is for one-to-one conversion between kana, as well the various full-width/half-width conversions necessary when dealing with Japanese text.  Its primary going to be used for normalization.

However, I do not see the purpose of this repository as translating between different types of Japanese text.  As you said, あたらしい becoming アタラシー would be common in modern Japanese, but it doesn't necessarily get written the way.  There are other words like 東京 which are regularly written in katakana as either トウキョウ or トーキョー.  That is ultimately a stylistic choice, which IMO is the realm of translation, not conversion.

To offer an example, the original reason I wanted a library like this (in Java) was when working on a database in which all Japanese kana text was converted to katakana for the purpose of normalizing it for prefix/suffix searches, like the kind of logic used in an autocomplete system.  This was done to avoid always searching both the hiragana, and katakana versions when users input text for autocomplete, it was more efficient to normalize all Japanese text to either hiragana or katakana.  Then we only have to perform one search whether a user inputs hiragana or katakana into a search box.  So in this kind of use case, and many others I imagine for this library, adding the logical long-vowel switch would effectively break that capability of one-to-one conversions.

**Comment by mariten** [comment]
Though if you wanted to add this as a conversion option, I would definitely welcome a pull request!

**Comment by stephenmac7** [comment]
Okay, so it looks like doing this won't work as well as I'd like for オー-type long vowels, because it could convert to う or to お depending on the context, ex. 王[おう] (オー) and 十[とお] (トー). It's not really one-to-one, so requires a bit more intelligence which isn't really part of the aim of this project. Thanks for looking into it though.
