### ISSUE TITLE
Wrong Katakana Range

### ISSUE THREAD

**Issue by stephenmac7** [mariten/kanatools-java#16]
The official range for Katakana goes from U+30A0-U+30FF, but it seems to be U+30A1-U+30FA in KanaAppraiser.java

**Comment by mariten** [comment]
Yea you're right.

The characters outside the range I've defined in KanaAppraiser.java are symbols and not actually "kana" per say, but there should be a way to indicate they are Japanese text at least.  Let me look into addressing this.

**Comment by mariten** [comment]
Hi @stephenmac7 ,

I'd like to note that the Unicode Block for Katakana and Hiragana is not the official definition of what is and is not actually Katakana and Hiragana (A Japanese dictionary or textbook is a much better authority on that matter).  Unicode blocks must be 16-chars long, so they tend to have extra chars lumped in, and both the hiragana and katakana blocks have some punctuation marks in them.

What I've done is include a new set of functions in **KanaAppraiser** to identify Japanese punctuation marks or *kutoten*, on their own as separate entities from hiragana/katakana.  These new functions are `isZenkakuKutoten` and `isHankakuKutoten`.  This now covers those extra chars in the Hiragana and Katakana Unicode blocks, as well as a few others from around the Unicode spectrum.

Please see the pull request mentioned above for the diff.

This issue has been addressed in v1.3.0 so I am considering it now closed.

Thanks for the contact.

**Comment by stephenmac7** [comment]
Okay, thanks. I understand that you want the Katakana range to only include actual Katakana instead of just the whole Katakana unicode block. At least now it's possible to detect them, so thank you!
